### ISSUE TITLE
could you change the license?

### ISSUE THREAD

**Issue by jonjoliver** [adamliesko/tlsh#1]
Hi

this is great. I am adding a link to it in
    https://github.com/trendmicro/tlsh

But you have made the license MIT - which is not actually allowed under the license of TLSH.
Could you make the LICENSE.txt file the same as
      https://github.com/trendmicro/tlsh/blob/master/LICENSE

Cheers
jono

**Comment by adamliesko** [comment]
Sure, wanted to discuss that (https://github.com/trendmicro/tlsh/pull/36). Done. 

Thank you
Adam
